name: Docker Nightly Build
on:
  push:
  pull_request:
  
jobs:
  nightly-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'false'
          remove-dotnet: 'true'
          remove-android: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: sewagepuppy
          password: Ilovedogshit69!
      -
        name: Set build date
        run: echo "BUILD_DATE=NIGHTLY $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          target: default
          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
          tags: guinnessshep/text-generation-webui:default-nightly
